sudo: false
language: elixir
elixir:
  - 1.6
  - 1.7
otp_release:
  - 20.0
  - 20.1
  - 20.2
  - 20.3
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
env: PATH=$PATH:.
cache:
  directories:
    - $HOME/.cache/rebar3/
script: "./bin/checks.sh && ./rebar3 coveralls send"
