sudo: false
language: elixir
install: 'true'
matrix:
  include:
    - otp_release: 18.3
      elixir: 1.3.2
    - otp_release: 19.0
      elixir: 1.3.2
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - mix deps.get --only test
env: PATH=$PATH:.
cache:
  directories:
    - $HOME/.cache/rebar3/
script: "./bin/checks.sh && ./rebar3 coveralls send"
